name: Generate Custom Snake

on:
  # Se ejecuta cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  #  permite ejecutarlo manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Trae el código del repositorio
      - uses: actions/checkout@v3

      # 2. Genera la animación con la nueva paleta de verdes brillantes
      - uses: Platane/snk@v3
        with:
          github_user_name: DilanRojasca
          
          #  PALETA DE COLORES! ---
          outputs: |
            dist/snake-generated.svg?color_snake=%230000FF&color_dots=%23161B22,%230E4429,%23006D32,%2326A641,%2339D353&color_bg=%23000000&color_grid=%23161B22

      # 3. nuevo archivo al repositorio
      - name: Push custom snake
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add dist/snake-generated.svg
          git commit -m "chore: generate custom snake" || exit 0
          git push
